<?php
function save_product(): void {
    if (($_SESSION['user']['rol']??'') !== 'admin') { http_response_code(403); exit('Solo administrador.'); }
    $name=trim($_POST['nombre']??''); $price=(float)($_POST['precio_venta']??0); $cost=(float)($_POST['precio_compra']??0); $stock=max(0,(int)($_POST['stock']??0)); $min=max(0,(int)($_POST['stock_minimo']??3)); $cat=(int)($_POST['id_categoria']??0);
    if($name==='' || $price<=0 || $cost<0) { header('Location: index.php?page=products&error=1'); exit; }
    $pdo=db(); $pdo->beginTransaction(); try { $s=$pdo->prepare('INSERT INTO productos(id_categoria,nombre,descripcion,precio_compra,precio_venta,activo) VALUES(?,?,?,?,?,1)'); $s->execute([$cat ?: null,$name,trim($_POST['descripcion']??''),$cost,$price]); $id=(int)$pdo->lastInsertId(); $s=$pdo->prepare('INSERT INTO inventario(id_producto,stock_actual,stock_minimo) VALUES(?,?,?)'); $s->execute([$id,$stock,$min]); $pdo->commit(); } catch(Throwable $e){$pdo->rollBack(); throw $e;}
    header('Location: index.php?page=products&saved=1'); exit;
}
function render_products(): void {
    $pdo=db(); $cats=$pdo->query('SELECT id_categoria,nombre FROM categorias ORDER BY nombre')->fetchAll(); $rows=$pdo->query('SELECT p.id_producto,p.nombre,p.precio_venta,c.nombre categoria,i.stock_actual,i.stock_minimo FROM productos p LEFT JOIN categorias c ON c.id_categoria=p.id_categoria LEFT JOIN inventario i ON i.id_producto=p.id_producto WHERE p.activo=1 ORDER BY p.nombre')->fetchAll();
    if(($_SESSION['user']['rol']??'')==='admin') { echo '<section class="panel"><h2>Registrar producto</h2><form class="form-grid" method="post" action="index.php?page=product-save"><input type="hidden" name="csrf" value="'.e(csrf_token()).'"><label>Nombre<input name="nombre" required></label><label>Categoría<select name="id_categoria"><option value="0">Sin categoría</option>'; foreach($cats as $c) echo '<option value="'.(int)$c['id_categoria'].'">'.e($c['nombre']).'</option>'; echo '</select></label><label>Precio de compra (S/)<input type="number" name="precio_compra" min="0" step="0.01" required></label><label>Precio de venta (S/)<input type="number" name="precio_venta" min="0.01" step="0.01" required></label><label>Stock inicial<input type="number" name="stock" min="0" value="0" required></label><label>Stock mínimo<input type="number" name="stock_minimo" min="0" value="3" required></label><label class="wide">Descripción<input name="descripcion"></label><div class="wide"><button class="btn primary">Guardar producto</button></div></form></section>'; }
    echo '<section class="panel"><div class="panel-head"><h2>Catálogo de productos</h2><span class="count">'.count($rows).' productos</span></div><table><tr><th>Producto</th><th>Categoría</th><th>Precio</th><th>Stock</th><th>Estado</th></tr>'; foreach($rows as $r) { $low=(int)$r['stock_actual'] <= (int)$r['stock_minimo']; echo '<tr><td>'.e($r['nombre']).'</td><td>'.e($r['categoria']??'—').'</td><td>'.money($r['precio_venta']).'</td><td>'.(int)$r['stock_actual'].'</td><td>'.($low?'<span class="warning">Stock bajo</span>':'<span class="success">Disponible</span>').'</td></tr>'; } echo '</table></section>';
}
