<?php
function save_sale(): void {
    $productIds=$_POST['producto']??[]; $quantities=$_POST['cantidad']??[]; $client=(int)($_POST['id_cliente']??0); $method=$_POST['metodo_pago']??'Efectivo';
    if(!is_array($productIds)||count($productIds)===0){header('Location: index.php?page=sales&error=empty');exit;}
    $pdo=db(); $pdo->beginTransaction();
    try {
        $items=[]; $total=0.0;
        foreach($productIds as $i=>$pid){$pid=(int)$pid;$qty=max(1,(int)($quantities[$i]??1));$q=$pdo->prepare('SELECT p.id_producto,p.precio_venta,p.nombre,i.stock_actual FROM productos p JOIN inventario i ON i.id_producto=p.id_producto WHERE p.id_producto=? AND p.activo=1 FOR UPDATE');$q->execute([$pid]);$p=$q->fetch();if(!$p||$p['stock_actual']<$qty)throw new RuntimeException('Stock insuficiente para '.($p['nombre']??'el producto'));$sub=$qty*(float)$p['precio_venta'];$items[]=[$p,$qty,$sub];$total+=$sub;}
        $s=$pdo->prepare("INSERT INTO ventas(id_cliente,id_empleado,fecha_venta,subtotal,descuento,total,estado) VALUES(?,?,NOW(),?,0,?,'Finalizada')");$s->execute([$client?:null,(int)$_SESSION['user']['id'],$total,$total]);$saleId=(int)$pdo->lastInsertId();
        foreach($items as [$p,$qty,$sub]){$s=$pdo->prepare('INSERT INTO detalle_venta(id_venta,id_producto,cantidad,precio_unitario,subtotal) VALUES(?,?,?,?,?)');$s->execute([$saleId,$p['id_producto'],$qty,$p['precio_venta'],$sub]);$s=$pdo->prepare('UPDATE inventario SET stock_actual=stock_actual-? WHERE id_producto=?');$s->execute([$qty,$p['id_producto']]);}
        $s=$pdo->prepare("INSERT INTO pagos(id_venta,monto,metodo_pago,estado_pago,fecha_pago) VALUES(?,?,?,'Pagado',NOW())");$s->execute([$saleId,$total,$method]);$pdo->commit();header('Location: index.php?page=sales&saved=1');exit;
    } catch(Throwable $e){$pdo->rollBack();header('Location: index.php?page=sales&error='.rawurlencode($e->getMessage()));exit;}
}
function render_sales(): void {
    $pdo=db(); $products=$pdo->query('SELECT p.id_producto,p.nombre,p.precio_venta,i.stock_actual FROM productos p JOIN inventario i ON i.id_producto=p.id_producto WHERE p.activo=1 AND i.stock_actual>0 ORDER BY p.nombre')->fetchAll();$clients=$pdo->query('SELECT id_cliente,nombres,apellidos FROM clientes ORDER BY nombres')->fetchAll();
    echo '<section class="panel"><h2>Registrar venta</h2><p class="muted">Selecciona producto, cantidad y método de pago. El stock se descuenta al confirmar.</p><form method="post" action="index.php?page=sale-save"><input type="hidden" name="csrf" value="'.e(csrf_token()).'"><div class="form-grid"><label>Cliente (opcional)<select name="id_cliente"><option value="0">Venta sin cliente</option>';foreach($clients as $c)echo '<option value="'.(int)$c['id_cliente'].'">'.e(trim($c['nombres'].' '.$c['apellidos'])).'</option>';echo '</select></label><label>Método de pago<select name="metodo_pago"><option>Efectivo</option><option>Yape</option><option>Plin</option><option>Tarjeta</option></select></label><label>Producto<select name="producto[]" required>';foreach($products as $p)echo '<option value="'.(int)$p['id_producto'].'">'.e($p['nombre']).' — '.money($p['precio_venta']).' (stock '.(int)$p['stock_actual'].')</option>';echo '</select></label><label>Cantidad<input type="number" name="cantidad[]" min="1" value="1" required></label><div class="wide"><button class="btn primary" '.(!$products?'disabled':'').'>Confirmar venta</button></div></div></form></section>';
    $rows=$pdo->query('SELECT v.id_venta,v.fecha_venta,v.total,v.estado,COALESCE(CONCAT(c.nombres," ",c.apellidos),"Cliente ocasional") cliente,u.nombre_usuario,p.metodo_pago FROM ventas v LEFT JOIN clientes c ON c.id_cliente=v.id_cliente LEFT JOIN usuarios u ON u.id_usuario=v.id_empleado LEFT JOIN pagos p ON p.id_venta=v.id_venta ORDER BY v.id_venta DESC LIMIT 100')->fetchAll();echo '<section class="panel"><h2>Historial de ventas</h2><table><tr><th>N.º</th><th>Fecha</th><th>Cliente</th><th>Empleado</th><th>Pago</th><th>Total</th><th>Estado</th></tr>';foreach($rows as $r)echo '<tr><td>#'.(int)$r['id_venta'].'</td><td>'.e($r['fecha_venta']).'</td><td>'.e($r['cliente']).'</td><td>'.e($r['nombre_usuario']??'—').'</td><td>'.e($r['metodo_pago']??'—').'</td><td>'.money($r['total']).'</td><td>'.e($r['estado']).'</td></tr>';echo '</table></section>';
}
